estoque/urls.py
from django.urls import path

from . import views

app_name = 'estoque'

urlpatterns = [
    path('', views.avisos, name='index'),
    path('avisos', views.avisos, name='avisos'),

    path('listar_produtos/', views.listar_produtos, name='listar_produtos'),
    path('detalhes_produto/<int:pk>',
         views.detalhes_produto, name='detalhes_produto'),
    path('alterar_estoque/<int:pk>',
         views.atualizar_estoque, name='alterar_estoque'),
    path('listar_pedidos/', views.listar_pedidos, name='listar_pedidos'),

    path('cadastrar_produto/', views.cadastrar_produto, name='cadastrar_produto'),
    path('alterar_produto/<int:pk>',
         views.atualizar_produto, name='alterar_produto'),

    path('acrescentar_estoque_central/<int:pk>',
         views.acrescentar_estoque_central, name='acrescentar_estoque_central'),
    path('aprovar_pedido/<int:pk>', views.aprovar_pedido, name='aprovar_pedido'),
    path('reprovar_pedido/<int:pk>', views.reprovar_pedido, name='reprovar_pedido'),
    path('cadastrar_filial/', views.cadastrar_filial, name='cadastrar_filial'),
    path('listar_filiais/', views.listar_filiais, name='listar_filiais'),

    path('listar_compras_central/', views.listar_compras_central,
         name='listar_compras_central'),

    path('adicionar_ao_carrinho/<int:pk>',
         views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('filial_pedido/<int:pk>', views.filial_pedido, name='filial_pedido'),

    path('carrinho/', views.carrinho, name='carrinho'),
    path('alterar_quantidade_carrinho/<int:pk>', views.alterar_quantidade_carrinho, name='alterar_quantidade_carrinho'),
    path('remover_do_carrinho/<int:pk>', views.remover_do_carrinho, name='remover_do_carrinho'),
    path('finalizar_carrinho/', views.finalizar_carrinho, name='finalizar_carrinho'),

    path('detalhes_carrinho/<int:pk>', views.detalhes_carrinho, name='detalhes_carrinho'),
    path('listar_carrinhos/', views.listar_carrinhos, name='listar_carrinhos'),

    path('imprimir_comprovante_carrinho_pdf/<int:pk>', views.imprimir_comprovante_carrinho_pdf, name='imprimir_comprovante_carrinho_pdf'),
    path('atualizar_filial/<int:pk>', views.atualizar_filial, name='atualizar_filial'),

    path('estatisticas/', views.estatisticas, name='estatisticas'),
]

sgp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('estoque.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

estoque/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.db.models import Q


class Produto(models.Model):
    nome = models.CharField(max_length=50)
    codigo = models.PositiveIntegerField(
        unique=True, validators=[MinValueValidator(0), MaxValueValidator(1000000)])
    valor = models.DecimalField(max_digits=6, decimal_places=2, validators=[
                                MinValueValidator(0), MaxValueValidator(1000000)])

    def get_absolute_url(self):
        return reverse("estoque:detalhes_produto", args=[str(self.id)])

    def __str__(self):
        return self.nome


class Empresa(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    # true = filial | false = central
    filial = models.BooleanField(default=True)
    endereco = models.CharField(max_length=50)

    def __str__(self):
        return self.usuario.username


class Estoque(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField(
        default=0, validators=[MinValueValidator(0), MaxValueValidator(1000000)])
    baixo_estoque = models.PositiveIntegerField(
        default=0, validators=[MinValueValidator(0), MaxValueValidator(1000000)])
    alto_estoque = models.PositiveIntegerField(
        default=0, validators=[MinValueValidator(0), MaxValueValidator(1000000)])

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['empresa', 'produto'], name='empresa_produto'),
        ]

    def get_absolute_url(self):
        return reverse("estoque:detalhes_produto", args=[str(self.id)])

    def clean(self):
        if self.baixo_estoque > self.alto_estoque:
            raise ValidationError(
                {'baixo_estoque': ["Baixo estoque maior que alto.", ]})

    def __str__(self):
        return self.empresa.usuario.username + ' - ' + self.produto.nome


class Carrinho(models.Model):
    ABERTO = False
    FECHADO = True

    status = models.BooleanField(default=ABERTO)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(1000000)], default=0)
    valor = models.DecimalField(max_digits=10, decimal_places=2, validators=[
                                MinValueValidator(0), MaxValueValidator(1000000)], default=0)

    data = models.DateTimeField(null=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['empresa'], condition=Q(status=False), name='carrinho_aberto'),
        ]

    def __str__(self):
        return str(self.id) + ' - ' + str(self.empresa) + ' - ' + str(self.status)


class CarrinhoProdutos(models.Model):
    carrinho = models.ForeignKey(Carrinho, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(1000000)])
    valor = models.DecimalField(max_digits=10, decimal_places=2, validators=[
                                MinValueValidator(0), MaxValueValidator(1000000)])

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['carrinho', 'produto'], name='carrinho_produto'),
        ]

    def __str__(self):
        return str(self.carrinho) + ' - ' + str(self.produto)


class PedidosFilial(models.Model):
    ABERTO = 0
    APROVADO = 1
    REPROVADO = 2

    STATUS_PEDIDO = [
        (ABERTO, 'Aberto'),
        (APROVADO, 'Aprovado'),
        (REPROVADO, 'Reprovado'),
    ]

    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    status = models.PositiveSmallIntegerField(choices=STATUS_PEDIDO, validators=[
                                              MinValueValidator(0), MaxValueValidator(2)], default=ABERTO)

    quantidade = models.PositiveIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(1000000)])
    valor = models.DecimalField(max_digits=10, decimal_places=2, validators=[
                                MinValueValidator(0), MaxValueValidator(1000000)])
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.produto.nome + ' - ' + str(self.data)


class ComprasCentral(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(1000000)])
    valor = models.DecimalField(max_digits=10, decimal_places=2, validators=[
                                MinValueValidator(0), MaxValueValidator(1000000)])
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.produto.nome + ' - ' + str(self.data)

estoque/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from datetime import datetime
from django.db.models import Sum, F, Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from .models import Estoque, Empresa, Produto, PedidosFilial, ComprasCentral, Carrinho, CarrinhoProdutos
from .utilidades import paginar, filtrar_valor, converter_data, filtrar_data, get_info
from .forms import ProdutoForm, EstoqueForm, EstoqueAtualizarForm, ComprasCentralForm, PedidosFilialForm, UsuarioForm, FilialForm, ValorCompraCentralForm, CarrinhoProdutosForm, UsuarioFormAtualizar, UsuarioFormSenha
from .gerar_csv import arq_carrinho, arq_compras_central, arq_pedidos, arq_carrinho_produtos
from .gerar_pdf import comprovante_carrinho


@login_required
def listar_produtos(request):
    produtos = Produto.objects.all().order_by('nome')

    page = request.GET.get('page', 1)
    query = request.GET.get('q')
    valor1 = request.GET.get('valor1')
    valor2 = request.GET.get('valor2')
    opcao_valor = request.GET.get('opcao_valor')

    if valor1:
        valor1 = float(valor1)
    if valor2:
        valor2 = float(valor2)

    if query:
        if query.isdigit():
            produtos = produtos.filter(codigo=query)
        else:
            produtos = produtos.filter(nome__icontains=query)

    if produtos:
        produtos = filtrar_valor(produtos, opcao_valor, valor1, valor2)

    produtos = paginar(produtos, page, 3)

    return render(request, 'estoque/listar_produtos.html', {'produtos': produtos})


@login_required
def atualizar_produto(request, pk):
    if request.user.is_superuser:
        produto = get_object_or_404(Produto, pk=pk)

        form = ProdutoForm(instance=produto)

        if request.method == "POST":
            form = ProdutoForm(data=request.POST, instance=produto)

            if form.is_valid():
                form.save()

                return HttpResponseRedirect(reverse('estoque:detalhes_produto', kwargs={'pk': produto.pk}))

        return render(request, 'estoque/alterar_produto.html', {'form': form, 'produto': produto})

    return render(request, 'estoque/alterar_produto.html')


@login_required
def atualizar_estoque(request, pk):
    usuario = get_object_or_404(Empresa, usuario=request.user)
    produto = get_object_or_404(Produto, pk=pk)

    try:
        estoque = Estoque.objects.get(empresa=usuario, produto=produto)
    except Estoque.DoesNotExist:
        return HttpResponseRedirect(reverse('estoque:detalhes_produto', kwargs={'pk': produto.pk}))

    form = EstoqueAtualizarForm(instance=estoque)

    if request.method == "POST":
        form = EstoqueAtualizarForm(data=request.POST, instance=estoque)

        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('estoque:detalhes_produto', kwargs={'pk': produto.pk}))

    return render(request, 'estoque/alterar_estoque.html', {'form': form, 'produto': produto})


@login_required
def cadastrar_produto(request):
    if request.user.is_superuser:
        if request.method == "POST":
            empresa = get_object_or_404(Empresa, usuario=request.user)
            produto_form = ProdutoForm(prefix='produto',data=request.POST)
            estoque_form = EstoqueForm(prefix='estoque',data=request.POST)
            valor_compra_form = ValorCompraCentralForm(prefix='val_compra',data=request.POST)

            if produto_form.is_valid() and estoque_form.is_valid() and valor_compra_form:
                produto = produto_form.save()

                estoque = estoque_form.save(commit=False)
                estoque.empresa = empresa
                estoque.produto = produto
                estoque.save()

                if estoque.quantidade > 0:
                    valor_compra = valor_compra_form.save(commit=False)
                    valor_compra.produto = produto
                    valor_compra.quantidade = estoque.quantidade
                    valor_compra.save()

                return HttpResponseRedirect(reverse('estoque:detalhes_produto', kwargs={'pk': produto.pk}))
        else:
            produto_form = ProdutoForm(prefix='produto')
            estoque_form = EstoqueForm(prefix='estoque')
            valor_compra_form = ValorCompraCentralForm(prefix='val_compra')

        return render(request, 'estoque/cadastro_produto.html', {'produto_form': produto_form, 'estoque_form': estoque_form, 'valor_compra_form': valor_compra_form})

    return render(request, 'estoque/cadastro_produto.html')


@login_required
def detalhes_produto(request, pk):
    usuario = get_object_or_404(Empresa, usuario=request.user)

    produto = get_object_or_404(Produto, pk=pk)
    try:
        estoque = Estoque.objects.get(empresa=usuario, produto=produto)
    except Estoque.DoesNotExist:
        estoque = None

    return render(request, 'estoque/detalhes_produto.html', {'produto': produto, 'estoque': estoque})


@login_required
def avisos(request):
    page1 = request.GET.get('bpage', 1)
    page2 = request.GET.get('apage', 1)

    usuario = get_object_or_404(Empresa, usuario=request.user)
    baixo = Estoque.objects.filter(
        Q(empresa=usuario) & Q(quantidade__lte=F('baixo_estoque'))).order_by('quantidade')
    alto = Estoque.objects.filter(
        Q(empresa=usuario) & Q(quantidade__gte=F('alto_estoque'))).order_by('-quantidade')

    baixo = paginar(baixo, page1, 3)
    alto = paginar(alto, page2, 3)

    return render(request, 'estoque/avisos.html', {'baixo': baixo, 'alto': alto})


@login_required
def acrescentar_estoque_central(request, pk):
    form = ComprasCentralForm()
    produto = get_object_or_404(Produto, pk=pk)

    if request.method == "POST":
        form = ComprasCentralForm(data=request.POST)

        if form.is_valid():
            usuario = get_object_or_404(Empresa, usuario=request.user)

            try:
                estoque = Estoque.objects.get(empresa=usuario, produto=produto)
            except Estoque.DoesNotExist:
                return HttpResponseRedirect(reverse('estoque:detalhes_produto', kwargs={'pk': produto.pk}))

            data = form.save(commit=False)
            data.produto = produto
            data.save()

            estoque.quantidade += data.quantidade
            estoque.save()

            return HttpResponseRedirect(reverse('estoque:detalhes_produto', kwargs={'pk': produto.pk}))

    return render(request, 'estoque/alterar_estoque.html', {'form': form, 'produto': produto, 'acrescentar': True})


@login_required
def filial_pedido(request, pk):
    if request.user.is_superuser:
        return render(request, 'estoque/filial_pedido.html')

    form = PedidosFilialForm()
    produto = get_object_or_404(Produto, pk=pk)

    if request.method == "POST":
        form = PedidosFilialForm(data=request.POST)

        if form.is_valid():
            empresa = get_object_or_404(Empresa, usuario=request.user)

            data = form.save(commit=False)
            data.empresa = empresa
            data.produto = produto

            valor = produto.valor * data.quantidade
            data.valor = valor

            data.save()

            return HttpResponseRedirect(reverse('estoque:detalhes_produto', kwargs={'pk': produto.pk}))

    return render(request, 'estoque/filial_pedido.html', {'form': form, 'produto': produto})


@login_required
def listar_pedidos(request):
    page = request.GET.get('page', 1)
    status_pedido = request.GET.get('status_pedido')
    nome_produto = request.GET.get('nome_produto')
    nome_empresa = request.GET.get('nome_empresa')
    d1 = request.GET.get('d1')
    d2 = request.GET.get('d2')
    opcao_data = request.GET.get('opcao_data')
    valor1 = request.GET.get('valor1')
    valor2 = request.GET.get('valor2')
    opcao_valor = request.GET.get('opcao_valor')
    imprimir = request.GET.get('imprimir')

    if valor1:
        valor1 = float(valor1)
    if valor2:
        valor2 = float(valor2)

    valor = qtd = 0
    data1, data2 = converter_data(opcao_data, d1, d2)

    if status_pedido == 'aprovado':
        status_pedido = PedidosFilial.APROVADO
    elif status_pedido == 'reprovado':
        status_pedido = PedidosFilial.REPROVADO
    else:
        status_pedido = PedidosFilial.ABERTO

    if request.user.is_superuser:
        pedidos = PedidosFilial.objects.filter(status=status_pedido)
    else:
        usuario = get_object_or_404(Empresa, usuario=request.user)
        pedidos = PedidosFilial.objects.filter(
            Q(status=status_pedido) & Q(empresa=usuario))

    if nome_produto:
        if nome_produto.isdigit():
            pedidos = pedidos.filter(produto__codigo=nome_produto)
        else:
            pedidos = pedidos.filter(produto__nome__icontains=nome_produto)

    if nome_empresa and request.user.is_superuser:
        pedidos = pedidos.filter(Q(empresa__usuario__username=nome_empresa))

    if pedidos:
        pedidos = filtrar_data(pedidos, opcao_data, data1, data2)
        if pedidos:
            pedidos = filtrar_valor(pedidos, opcao_valor, valor1, valor2)
            if pedidos:
                valor, qtd = get_info(pedidos)

        pedidos = pedidos.order_by('-data')

    info = {
        'valor': valor,
        'qtd': qtd,
        'data1': data1,
        'data2': data2,
    }

    if imprimir:
        return arq_pedidos(pedidos, info, opcao_valor, valor1, valor2, opcao_data, nome_produto, nome_empresa, request.user, status_pedido)

    pedidos = paginar(pedidos, page, 3)

    return render(request, 'estoque/listar_pedidos.html', {'pedidos': pedidos, 'status_pedido': status_pedido, 'info': info})


@login_required
def aprovar_pedido(request, pk):
    if request.user.is_superuser:
        pedido = PedidosFilial.objects.get(pk=pk)

        if pedido.status == PedidosFilial.APROVADO:

estoque/templates/estoque/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- <title>Cadastro Produto</title> -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body style="background-color: #EDF5E1;">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="#"><img src="{% static 'images/logo_3_cor.png' %}" width="50" height="50" alt="logo"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'estoque:avisos' %}">Avisos<span
                            class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'estoque:listar_produtos' %}">Produtos<span
                            class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'estoque:listar_pedidos' %}">Pedidos<span
                            class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'estoque:listar_carrinhos' %}">Vendas<span
                            class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'estoque:estatisticas' %}">Estatísticas<span
                            class="sr-only">(current)</span></a>
                </li>

                {% if request.user.is_superuser %}

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'estoque:listar_compras_central' %}">Acrescimos<span
                            class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'estoque:listar_filiais' %}">Filiais<span
                            class="sr-only">(current)</span></a>
                </li>

                {% else %}

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'estoque:carrinho' %}">Carrinho<span
                            class="sr-only">(current)</span></a>
                </li>

                {% endif %}
            </ul>

            <a class="nav-link" href="#"><img src="{% static 'icons/person.svg' %}" class="img-fluid" alt="icone"> Logado como: {{ user.username }}</a>
            <a class="nav-link" href="{% url 'logout' %}"><img src="{% static 'icons/sign-out.svg' %}" class="img-fluid" alt="icone"> Encerrar Sessão<span class="sr-only">(current)</span></a>

        </div>
    </nav>

    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                {% block corpo %}
                {% endblock %}
            </div>
            <div class="col-md-1"></div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

estoque/templates/estoque/detalhes_produto.html
{% extends "estoque/base.html" %}

{% block corpo %}


<h1>Detalhes do Produto: {{ produto.nome }}</h1>

<hr>

<div class="row">
    {% if request.user.is_superuser %}
    <div class="col-lg">
        <a href="{% url 'estoque:alterar_produto' produto.pk %}"
            class="btn btn-sm btn-outline-primary btn-block">Atualizar
            Produto</a>
    </div>

    <div class="col-lg">
        <a href="{% url 'estoque:acrescentar_estoque_central' produto.pk %}"
            class="btn btn-sm btn-outline-primary btn-block">Acrescentar estoque</a>
    </div>
    {% else %}
    <div class="col-lg">
        <a href="{% url 'estoque:adicionar_ao_carrinho' produto.pk %}" class="btn btn-sm btn-outline-primary btn-block">Adicionar ao carrinho</a>
    </div>

    <div class="col-lg">
        <a href="{% url 'estoque:filial_pedido' produto.pk %}" class="btn btn-sm btn-outline-primary btn-block">Fazer
            Pedido</a>
    </div>
    {% endif %}

    <div class="col-lg">
        <a href="{% url 'estoque:alterar_estoque' produto.pk %}"
            class="btn btn-sm btn-outline-primary btn-block">Atualizar Baixo/Alto</a>
    </div>
</div>

<hr>

<table class="table table-striped table-bordered">
    <tr>
        <td>Codigo</td>
        <td>{{ produto.codigo }}</td>
    </tr>
    <tr>
        <td>Nome</td>
        <td>{{ produto.nome }}</td>
    </tr>
    <tr>
        <td>Preço</td>
        <td>{{ produto.valor }}</td>
    </tr>

    <tr>
        <td colspan="2">
            <strong>
                {% if estoque.quantidade > 0 %}
                Disponível no estoque
                {% else %}
                Produto não disponivel no estoque
                {% endif %}
            </strong>
        </td>
    </tr>

    {% if estoque %}
    <tr>
        <td>Quantidade</td>
        <td>{{ estoque.quantidade }}</td>
    </tr>
    <tr>
        <td>Baixo Estoque</td>
        <td>{{ estoque.baixo_estoque }}</td>
    </tr>
    <tr>
        <td>Alto Estoque</td>
        <td>{{ estoque.alto_estoque }}</td>
    </tr>
    {% endif %}

</table>

{% endblock %}

estoque/templates/estoque/listar_filiais.html
{% extends 'estoque/base.html' %}
{% load static %}
{% block corpo %}

{% if request.user.is_superuser %}

<h1>Filiais</h1>

<hr>

<form class="form-group" method="GET" action="{% url 'estoque:listar_filiais' %}">
    <div class="form-row align-items-center">
        <div class="form-group col">
            <input class="form-control form-control-sm" type="text" placeholder="Usuário" aria-label="Search"
                name="usuario">
        </div>
        <div class="form-group col">
            <input class="form-control form-control-sm" type="text" placeholder="Email" aria-label="Search"
                name="email">
        </div>
        <div class="form-group col">
            <input class="form-control form-control-sm" type="text" placeholder="Endereço" aria-label="Search"
                name="endereco">
        </div>
        <div class="form-group col">
            <button class="btn btn-outline-primary btn-sm" type="submit">Pesquisar <img src="{% static 'icons/search.svg' %}" class="img-fluid" alt="icone"></button>
        </div>
    </div>
</form>

<a href="{% url 'estoque:cadastrar_filial' %}" class="btn btn-outline-success btn-block btn-sm">Cadastrar Filial</a>

<hr>

<strong>
    Resultado da busca

    {% if request.GET.usuario %}
    | Nome: {{ request.GET.usuario }}
    {% else %}
    | Nome: Tudo
    {% endif %}

    {% if request.GET.email %}
    | Email: {{ request.GET.email }}
    {% else %}
    | Email: Tudo
    {% endif %}

    {% if request.GET.endereco %}
    | Endereco: {{ request.GET.endereco }}
    {% else %}
    | Endereco: Tudo
    {% endif %}
</strong>

<div class="table-responsive">
    <table class="table table-striped table-bordered table-sm">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Usuario</th>
                <th scope="col">Email</th>
                <th scope="col">Endereço</th>
                <th scope="col">Opções</th>
            </tr>
        </thead>
        <tbody>
            {% for filial in filiais %}
            <tr>
                <td>
                    {{ filial.usuario.username }}
                </td>
                <td>
                    {{ filial.usuario.email }}
                </td>
                <td>
                    {{ filial.endereco }}
                </td>
                <td>
                    <a href="{% url 'estoque:atualizar_filial' filial.pk %}">Atualizar</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan=4>
                    <h4>Nenhum resultado encontrado.</h4>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% if filiais.has_other_pages %}

<ul class="pagination float-right">
    <li class="page-item">
        <span class="page-link">{{ filiais.number }}/{{ filiais.paginator.num_pages }}</span>
    </li>

    {% if filiais.has_previous %}
    <li class="page-item"><a class="page-link"
            href="?usuario={{ request.GET.usuario }}&email={{ request.GET.email }}&endereco={{ request.GET.endereco }}&page={{ filiais.previous_page_number }}">Anterior</a>
    </li>
    {% else %}
    <li class="page-item disabled"><span class="page-link">Anterior</span></li>
    {% endif %}

    {% if filiais.has_next %}
    <li class="page-item"><a class="page-link"
            href="?usuario={{ request.GET.usuario }}&email={{ request.GET.email }}&endereco={{ request.GET.endereco }}&page={{ filiais.next_page_number }}">Proxima</a>
    </li>
    {% else %}
    <li class="page-item disabled"><span class="page-link">Proxima</span></li>
    {% endif %}

</ul>
{% endif %}

{% else %}
<h3>Você não possui permissão para concluir esta ação.</h3>
<hr>
<a href="{% url 'estoque:avisos' %}" class="btn btn-block btn-primary">Retornar</a>

{% endif %}

{% endblock %}